---
title: "Standard Curve and Sample Estimation"
author: "Lee Kennedy"
date: "6 April 2016"
output: html_document
---

This script fits a power curve to a set standards and then estimates the sample concentration from that curve.


## Curve Data

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library (readxl)
library(dplyr)
library(ggplot2)

data.in <- read_excel("data/Power_Data.xlsx", sheet = 1)

all_curve_data <- round(data.in[,c(3,4)],2)
all_curve_data
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}

blank <- as.numeric(data.in[1,4])

curve_data <- data.in[-1,c(3,4)]

units <- as.character(data.in[1,2])

n <- nrow(curve_data)

for (i in 1:n){
        curve_data$Reading_std[i] <- curve_data$Reading_std[i]-blank
}

curve_data <- curve_data %>%
        mutate(logV = log10(Standard), logR = log10(Reading_std))

fit <- lm(logR ~ logV, data = curve_data)

```


## Equation co-efficients:

```{r, echo=FALSE, message=FALSE, warning=FALSE}
a <- 10^summary(fit)[[4]][1][1][1]
b <- summary(fit)[[4]][2][1][1]
R2 <- round(summary(fit)[[8]][1], 3)

```

The equation for the curve is of the form: Result = blank + a*(Reading)^b where 


Parameter | Result     
----------|------------
blank     | `r blank`  
a         | `r a`      
b         | `r b`      
R2        | `r R2`     


## Standard Curve

```{r, echo = FALSE}

x_c <- seq(from = 1, to = max(curve_data$Standard), by = 1)
y_c <- blank + a*(x_c)^b

curve_line <- as.data.frame(cbind(x_c, y_c))

curve_plot <- ggplot(curve_line, aes(x=x_c, y=y_c)) +
        geom_line() +
        geom_point(data=data.in, aes(x=Standard, y = Reading_std), 
                   size=4, 
                   shape=21, 
                   fill = "cornflowerblue", 
                   colour = "black") +
        theme_bw() +
        theme(panel.grid.major = element_line(size = 0.5, color = "grey"), 
              axis.line = element_line(size = 0.7, color = "black"), 
              text = element_text(size = 14)) +
        labs(x=units, y="Reading")

curve_plot
```

##  Sample Results

```{r, echo=FALSE}
sample_data <- as.data.frame(na.omit(data.in[,5]))

results <- sample_data %>%
        mutate(Result = round(10^((log10(Reading-blank)-log10(a))/b),2))
colnames(results)[2] <- "mg/L"
results
```


